import type { Cuisine, DietType, Goal, Macros, MealSlot, RecipeStep } from '@/types'

export interface RecipeIngredientTemplate {
  name: string
  quantity: string
  ingredientId?: string
}

export interface RecipeTemplate {
  id: string
  name: string
  description: string
  cuisine: Cuisine
  dietType: DietType
  suitableSlots: MealSlot[]
  baseCalories: number
  macros: Macros
  servings: number
  totalTimeMinutes: number
  ingredients: RecipeIngredientTemplate[]
  steps: RecipeStep[]
  tags: Goal[]
}

export const RECIPE_TEMPLATES: RecipeTemplate[] = [
  // ---------------- Maharashtrian · Vegetarian ----------------
  {
    id: 'mh-poha',
    name: 'Kanda Poha',
    description: 'Flattened rice tempered with onion, peanuts, and curry leaves.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast', 'Evening Snack'],
    baseCalories: 260,
    macros: { protein: 6, carbs: 42, fats: 8 },
    servings: 2,
    totalTimeMinutes: 20,
    ingredients: [
      { name: 'Flattened Rice (Poha)', quantity: '2 cups', ingredientId: 'flattened-rice' },
      { name: 'Onion', quantity: '1, finely chopped', ingredientId: 'onion' },
      { name: 'Peanuts', quantity: '2 tbsp', ingredientId: 'peanuts' },
      { name: 'Mustard Seeds', quantity: '1 tsp', ingredientId: 'mustard-seeds' },
      { name: 'Curry Leaves', quantity: '8-10', ingredientId: 'curry-leaves' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
      { name: 'Green Chilli', quantity: '2, slit', ingredientId: 'green-chilli' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
    ],
    steps: [
      { text: 'Rinse poha in a colander until soft; drain and set aside.', minutes: 5 },
      { text: 'Heat oil, crackle mustard seeds, add peanuts and curry leaves.', minutes: 3 },
      { text: 'Add onion and green chilli, sauté until translucent.', minutes: 5 },
      { text: 'Add turmeric and poha, toss gently to combine and heat through.', minutes: 5 },
      { text: 'Finish with lemon juice and fresh coriander.', minutes: 2 },
    ],
    tags: ['Balanced', 'Low Sugar'],
  },
  {
    id: 'mh-sabudana-khichdi',
    name: 'Sabudana Khichdi',
    description: 'Sago pearls with peanuts, cumin and a squeeze of lime.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast', 'Evening Snack'],
    baseCalories: 320,
    macros: { protein: 7, carbs: 48, fats: 12 },
    servings: 2,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Sago (Sabudana)', quantity: '1.5 cups, soaked' },
      { name: 'Peanuts', quantity: '3 tbsp, crushed', ingredientId: 'peanuts' },
      { name: 'Potato', quantity: '1, diced', ingredientId: 'potato' },
      { name: 'Cumin Seeds', quantity: '1 tsp', ingredientId: 'cumin-seeds' },
      { name: 'Green Chilli', quantity: '2, chopped', ingredientId: 'green-chilli' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
    ],
    steps: [
      { text: 'Soak sabudana for 4-5 hours until pearls turn soft, drain excess water.', minutes: 5 },
      { text: 'Heat ghee, add cumin seeds and diced potato; cook until tender.', minutes: 8 },
      { text: 'Add green chilli and crushed peanuts, stir briefly.', minutes: 3 },
      { text: 'Fold in sabudana, cook on low flame until translucent.', minutes: 7 },
      { text: 'Finish with lemon juice and rock salt.', minutes: 2 },
    ],
    tags: ['Balanced'],
  },
  {
    id: 'mh-thalipeeth',
    name: 'Thalipeeth',
    description: 'Multigrain savoury pancake with onion and spices.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast', 'Evening Snack'],
    baseCalories: 280,
    macros: { protein: 9, carbs: 40, fats: 9 },
    servings: 2,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Multigrain Flour (Jowar/Bajri blend)', quantity: '1.5 cups', ingredientId: 'sorghum' },
      { name: 'Onion', quantity: '1, finely chopped', ingredientId: 'onion' },
      { name: 'Coriander Leaves', quantity: '2 tbsp', ingredientId: 'coriander-leaves' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
      { name: 'Green Chilli', quantity: '1, minced', ingredientId: 'green-chilli' },
    ],
    steps: [
      { text: 'Combine flour, onion, coriander, chilli and turmeric with water into a soft dough.', minutes: 8 },
      { text: 'Pat portions directly onto a hot griddle into thin discs.', minutes: 6 },
      { text: 'Drizzle oil around edges, cover and cook until golden on both sides.', minutes: 10 },
      { text: 'Serve hot with curd or a dab of butter.', minutes: 1 },
    ],
    tags: ['High Fiber', 'Balanced'],
  },
  {
    id: 'mh-amti',
    name: 'Varan Amti',
    description: 'Tangy-sweet Maharashtrian dal with kokum and jaggery.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 240,
    macros: { protein: 13, carbs: 32, fats: 6 },
    servings: 3,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Pigeon Pea Lentils (Toor Dal)', quantity: '1 cup', ingredientId: 'toor-dal' },
      { name: 'Jaggery', quantity: '1 tbsp', ingredientId: 'jaggery' },
      { name: 'Tamarind', quantity: 'small ball', ingredientId: 'tamarind' },
      { name: 'Curry Leaves', quantity: '6-8', ingredientId: 'curry-leaves' },
      { name: 'Mustard Seeds', quantity: '1 tsp', ingredientId: 'mustard-seeds' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Pressure cook dal with turmeric until soft; whisk smooth.', minutes: 15 },
      { text: 'Prepare tadka of mustard seeds and curry leaves in hot ghee.', minutes: 3 },
      { text: 'Pour tadka into dal, add jaggery and tamarind pulp.', minutes: 5 },
      { text: 'Simmer 8-10 minutes until flavours meld.', minutes: 8 },
    ],
    tags: ['Protein-Rich', 'Balanced'],
  },
  {
    id: 'mh-batata-bhaji',
    name: 'Batata Bhaji',
    description: 'Dry-tempered potato curry, classic accompaniment to poori or bhakri.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 220,
    macros: { protein: 4, carbs: 34, fats: 8 },
    servings: 3,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Potato', quantity: '3, boiled and cubed', ingredientId: 'potato' },
      { name: 'Onion', quantity: '1, sliced', ingredientId: 'onion' },
      { name: 'Mustard Seeds', quantity: '1 tsp', ingredientId: 'mustard-seeds' },
      { name: 'Curry Leaves', quantity: '6-8', ingredientId: 'curry-leaves' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
      { name: 'Green Chilli', quantity: '2, slit', ingredientId: 'green-chilli' },
    ],
    steps: [
      { text: 'Crackle mustard seeds and curry leaves in hot oil.', minutes: 2 },
      { text: 'Add onion and green chilli, sauté until soft.', minutes: 6 },
      { text: 'Add turmeric and boiled potatoes, toss to coat evenly.', minutes: 8 },
      { text: 'Cook uncovered until lightly golden at the edges.', minutes: 8 },
    ],
    tags: ['Balanced', 'Low Sugar'],
  },
  {
    id: 'mh-zunka-bhakri',
    name: 'Zunka with Bhakri',
    description: 'Spiced chickpea-flour crumble served with jowar flatbread.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 300,
    macros: { protein: 11, carbs: 38, fats: 11 },
    servings: 2,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Chickpea Flour (Besan)', quantity: '1 cup', ingredientId: 'chickpea-flour' },
      { name: 'Sorghum Flour (Jowar)', quantity: '1.5 cups', ingredientId: 'sorghum' },
      { name: 'Onion', quantity: '1, chopped', ingredientId: 'onion' },
      { name: 'Garlic', quantity: '4 cloves', ingredientId: 'garlic' },
      { name: 'Green Chilli', quantity: '2', ingredientId: 'green-chilli' },
    ],
    steps: [
      { text: 'Knead jowar flour with warm water; pat into thin bhakris and roast on tawa.', minutes: 15 },
      { text: 'Sauté onion, garlic and chilli in oil until fragrant.', minutes: 5 },
      { text: 'Sprinkle besan over, roast on low flame stirring continuously.', minutes: 6 },
      { text: 'Add water gradually to reach a crumbly consistency; season and simmer.', minutes: 6 },
    ],
    tags: ['High Fiber', 'Balanced'],
  },
  {
    id: 'mh-misal',
    name: 'Misal',
    description: 'Spicy sprouted moth bean curry topped with farsan and onion.',
    cuisine: 'Maharashtrian',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast', 'Lunch'],
    baseCalories: 350,
    macros: { protein: 15, carbs: 44, fats: 12 },
    servings: 2,
    totalTimeMinutes: 35,
    ingredients: [
      { name: 'Moth Beans (Matki), sprouted', quantity: '1.5 cups', ingredientId: 'moth-beans' },
      { name: 'Onion', quantity: '1, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '1, chopped', ingredientId: 'tomato' },
      { name: 'Coconut', quantity: '2 tbsp, grated', ingredientId: 'coconut' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Sauté onion, tomato and coconut into a smooth masala base.', minutes: 10 },
      { text: 'Add sprouted matki and turmeric, cook with water until tender.', minutes: 18 },
      { text: 'Simmer to a thin curry consistency; season to taste.', minutes: 5 },
      { text: 'Top with chopped onion, coriander and sev before serving.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'High Fiber'],
  },

  // ---------------- Maharashtrian · Non-Vegetarian ----------------
  {
    id: 'mh-chicken-sukka',
    name: 'Chicken Sukka',
    description: 'Dry-roasted chicken tossed in coconut and Kolhapuri spices.',
    cuisine: 'Maharashtrian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 380,
    macros: { protein: 34, carbs: 10, fats: 22 },
    servings: 3,
    totalTimeMinutes: 40,
    ingredients: [
      { name: 'Chicken', quantity: '500g, cut into pieces', ingredientId: 'chicken' },
      { name: 'Onion', quantity: '2, sliced', ingredientId: 'onion' },
      { name: 'Coconut', quantity: '1/2 cup, grated', ingredientId: 'coconut' },
      { name: 'Garlic', quantity: '6 cloves', ingredientId: 'garlic' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
      { name: 'Turmeric', quantity: '1 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Marinate chicken with turmeric and salt for 15 minutes.', minutes: 15 },
      { text: 'Dry roast coconut until golden; grind with garlic and ginger.', minutes: 8 },
      { text: 'Sauté onions until deep brown, add chicken and sear.', minutes: 10 },
      { text: 'Add ground masala, cover and cook until chicken is tender and dry.', minutes: 15 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'mh-kolambi-curry',
    name: 'Kolambi (Prawn) Curry',
    description: 'Coastal Maharashtrian prawn curry in a coconut-tamarind gravy.',
    cuisine: 'Maharashtrian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 340,
    macros: { protein: 30, carbs: 12, fats: 18 },
    servings: 3,
    totalTimeMinutes: 35,
    ingredients: [
      { name: 'Prawns', quantity: '400g, cleaned', ingredientId: 'prawns' },
      { name: 'Coconut', quantity: '1/2 cup, grated', ingredientId: 'coconut' },
      { name: 'Onion', quantity: '1, chopped', ingredientId: 'onion' },
      { name: 'Tamarind', quantity: 'small ball', ingredientId: 'tamarind' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Grind coconut with onion into a smooth masala paste.', minutes: 8 },
      { text: 'Sauté paste in oil until aroma releases and oil separates.', minutes: 8 },
      { text: 'Add tamarind pulp, turmeric and water; bring to a simmer.', minutes: 6 },
      { text: 'Add prawns, cook 6-8 minutes until just opaque.', minutes: 8 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'mh-mutton-rassa',
    name: 'Mutton Rassa',
    description: 'Fiery Kolhapuri-style mutton curry with a thin spiced gravy.',
    cuisine: 'Maharashtrian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 420,
    macros: { protein: 32, carbs: 10, fats: 26 },
    servings: 4,
    totalTimeMinutes: 55,
    ingredients: [
      { name: 'Mutton', quantity: '600g', ingredientId: 'mutton' },
      { name: 'Onion', quantity: '3, sliced', ingredientId: 'onion' },
      { name: 'Coconut', quantity: '1/3 cup, grated', ingredientId: 'coconut' },
      { name: 'Garlic', quantity: '8 cloves', ingredientId: 'garlic' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
    ],
    steps: [
      { text: 'Pressure cook mutton with ginger-garlic paste until tender.', minutes: 25 },
      { text: 'Roast onions and coconut separately until deep brown; grind fine.', minutes: 10 },
      { text: 'Simmer ground masala in oil, add cooked mutton with stock.', minutes: 15 },
      { text: 'Simmer until the rassa (thin gravy) reaches desired consistency.', minutes: 10 },
    ],
    tags: ['Protein-Rich'],
  },

  // ---------------- Indian · Vegetarian ----------------
  {
    id: 'in-dal-tadka',
    name: 'Dal Tadka',
    description: 'Yellow lentils finished with a smoky cumin-garlic tempering.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 260,
    macros: { protein: 15, carbs: 34, fats: 7 },
    servings: 3,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Split Green Gram (Moong Dal)', quantity: '1 cup', ingredientId: 'moong-dal' },
      { name: 'Tomato', quantity: '2, chopped', ingredientId: 'tomato' },
      { name: 'Garlic', quantity: '5 cloves', ingredientId: 'garlic' },
      { name: 'Cumin Seeds', quantity: '1 tsp', ingredientId: 'cumin-seeds' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Pressure cook dal with turmeric until soft.', minutes: 15 },
      { text: 'Sauté tomato until pulpy, add to cooked dal and simmer.', minutes: 8 },
      { text: 'Prepare a tadka of cumin and garlic in ghee, pour over dal.', minutes: 5 },
      { text: 'Garnish with fresh coriander before serving.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'Balanced'],
  },
  {
    id: 'in-paneer-bhurji',
    name: 'Paneer Bhurji',
    description: 'Scrambled cottage cheese with onion, tomato and mild spice.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast', 'Lunch', 'Dinner'],
    baseCalories: 310,
    macros: { protein: 20, carbs: 10, fats: 20 },
    servings: 2,
    totalTimeMinutes: 20,
    ingredients: [
      { name: 'Paneer', quantity: '250g, crumbled', ingredientId: 'paneer' },
      { name: 'Onion', quantity: '1, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '1, chopped', ingredientId: 'tomato' },
      { name: 'Capsicum', quantity: '1, diced', ingredientId: 'capsicum' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
    ],
    steps: [
      { text: 'Sauté onion until translucent, add capsicum and tomato.', minutes: 6 },
      { text: 'Add turmeric and cook until tomato softens.', minutes: 4 },
      { text: 'Fold in crumbled paneer, cook 4-5 minutes on medium heat.', minutes: 5 },
      { text: 'Finish with coriander and a squeeze of lemon.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'in-chana-masala',
    name: 'Chana Masala',
    description: 'Chickpeas simmered in a tangy onion-tomato masala.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 300,
    macros: { protein: 14, carbs: 44, fats: 8 },
    servings: 3,
    totalTimeMinutes: 35,
    ingredients: [
      { name: 'Chickpeas', quantity: '1.5 cups, boiled', ingredientId: 'chickpeas' },
      { name: 'Onion', quantity: '2, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '2, pureed', ingredientId: 'tomato' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
      { name: 'Garlic', quantity: '5 cloves', ingredientId: 'garlic' },
    ],
    steps: [
      { text: 'Sauté onion until golden, add ginger-garlic paste.', minutes: 6 },
      { text: 'Add tomato puree and spices, cook until oil separates.', minutes: 10 },
      { text: 'Add boiled chickpeas with a little water, simmer.', minutes: 15 },
      { text: 'Mash a few chickpeas to thicken; adjust seasoning.', minutes: 4 },
    ],
    tags: ['Protein-Rich', 'High Fiber'],
  },
  {
    id: 'in-veg-pulao',
    name: 'Vegetable Pulao',
    description: 'Fragrant one-pot rice with seasonal vegetables and whole spices.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 340,
    macros: { protein: 8, carbs: 58, fats: 9 },
    servings: 3,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Rice', quantity: '1.5 cups', ingredientId: 'rice' },
      { name: 'Green Peas', quantity: '1/2 cup', ingredientId: 'green-peas' },
      { name: 'Carrot', quantity: '1, diced' },
      { name: 'Onion', quantity: '1, sliced', ingredientId: 'onion' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
    ],
    steps: [
      { text: 'Sauté onion in ghee with whole spices until golden.', minutes: 6 },
      { text: 'Add vegetables and ginger, sauté briefly.', minutes: 4 },
      { text: 'Add soaked rice and water in 1:1.5 ratio, bring to a boil.', minutes: 5 },
      { text: 'Cover and cook on low heat until rice is fluffy.', minutes: 15 },
    ],
    tags: ['Balanced'],
  },
  {
    id: 'in-idli-sambar',
    name: 'Idli with Sambar',
    description: 'Steamed rice cakes served with a tangy lentil-vegetable stew.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast'],
    baseCalories: 280,
    macros: { protein: 11, carbs: 50, fats: 4 },
    servings: 2,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Idli Batter', quantity: '2 cups' },
      { name: 'Pigeon Pea Lentils (Toor Dal)', quantity: '1/2 cup', ingredientId: 'toor-dal' },
      { name: 'Tamarind', quantity: 'small ball', ingredientId: 'tamarind' },
      { name: 'Carrot', quantity: '1, diced' },
      { name: 'Curry Leaves', quantity: '6-8', ingredientId: 'curry-leaves' },
    ],
    steps: [
      { text: 'Steam idli batter in moulds for 10-12 minutes.', minutes: 12 },
      { text: 'Cook dal until soft, whisk smooth.', minutes: 12 },
      { text: 'Add tamarind pulp, vegetables and sambar powder, simmer.', minutes: 10 },
      { text: 'Temper with mustard seeds and curry leaves; serve hot.', minutes: 3 },
    ],
    tags: ['Low Carbs', 'High Fiber'],
  },
  {
    id: 'in-moong-cheela',
    name: 'Moong Dal Cheela',
    description: 'Savoury lentil crepes, light and protein-packed.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast', 'Evening Snack'],
    baseCalories: 220,
    macros: { protein: 14, carbs: 28, fats: 5 },
    servings: 2,
    totalTimeMinutes: 20,
    ingredients: [
      { name: 'Split Green Gram (Moong Dal)', quantity: '1 cup, soaked', ingredientId: 'moong-dal' },
      { name: 'Onion', quantity: '1, finely chopped', ingredientId: 'onion' },
      { name: 'Ginger', quantity: '1/2 inch', ingredientId: 'ginger' },
      { name: 'Green Chilli', quantity: '1', ingredientId: 'green-chilli' },
    ],
    steps: [
      { text: 'Grind soaked dal with ginger and chilli into a smooth batter.', minutes: 6 },
      { text: 'Stir in chopped onion and season with salt.', minutes: 2 },
      { text: 'Spread a ladle of batter thin on a hot griddle.', minutes: 3 },
      { text: 'Drizzle oil, cook both sides until golden and crisp.', minutes: 8 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'in-rajma-chawal',
    name: 'Rajma Chawal',
    description: 'Kidney bean curry served over steamed rice.',
    cuisine: 'Indian',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 380,
    macros: { protein: 16, carbs: 60, fats: 8 },
    servings: 3,
    totalTimeMinutes: 40,
    ingredients: [
      { name: 'Kidney Beans (Rajma)', quantity: '1.5 cups, boiled' },
      { name: 'Rice', quantity: '1.5 cups', ingredientId: 'rice' },
      { name: 'Onion', quantity: '2, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '2, pureed', ingredientId: 'tomato' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
    ],
    steps: [
      { text: 'Cook rice separately until fluffy.', minutes: 15 },
      { text: 'Sauté onion, ginger and tomato puree into a thick base.', minutes: 10 },
      { text: 'Add boiled rajma with cooking liquid, simmer until thick.', minutes: 15 },
      { text: 'Mash lightly for a creamy texture; serve over rice.', minutes: 3 },
    ],
    tags: ['Protein-Rich', 'High Fiber'],
  },

  // ---------------- Indian · Non-Vegetarian ----------------
  {
    id: 'in-egg-curry',
    name: 'Egg Curry',
    description: 'Boiled eggs simmered in a spiced onion-tomato gravy.',
    cuisine: 'Indian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 300,
    macros: { protein: 18, carbs: 14, fats: 20 },
    servings: 2,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Egg', quantity: '4, boiled', ingredientId: 'egg' },
      { name: 'Onion', quantity: '2, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '2, pureed', ingredientId: 'tomato' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
      { name: 'Garlic', quantity: '5 cloves', ingredientId: 'garlic' },
    ],
    steps: [
      { text: 'Sauté onion until golden, add ginger-garlic paste.', minutes: 6 },
      { text: 'Add tomato puree and spices, cook until oil separates.', minutes: 10 },
      { text: 'Add water to form a gravy, simmer 8 minutes.', minutes: 8 },
      { text: 'Add halved boiled eggs, simmer 5 minutes to absorb flavour.', minutes: 5 },
    ],
    tags: ['Protein-Rich'],
  },
  {
    id: 'in-chicken-curry',
    name: 'Home-style Chicken Curry',
    description: 'Everyday chicken curry with a warm onion-tomato masala.',
    cuisine: 'Indian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 360,
    macros: { protein: 32, carbs: 12, fats: 20 },
    servings: 3,
    totalTimeMinutes: 45,
    ingredients: [
      { name: 'Chicken', quantity: '500g', ingredientId: 'chicken' },
      { name: 'Onion', quantity: '2, sliced', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '2, pureed', ingredientId: 'tomato' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
      { name: 'Garlic', quantity: '6 cloves', ingredientId: 'garlic' },
    ],
    steps: [
      { text: 'Marinate chicken with ginger-garlic paste and salt.', minutes: 15 },
      { text: 'Sauté onions until deep golden, add tomato puree and spices.', minutes: 10 },
      { text: 'Add chicken, sear on all sides.', minutes: 8 },
      { text: 'Add water, cover and simmer until chicken is cooked through.', minutes: 15 },
    ],
    tags: ['Protein-Rich'],
  },
  {
    id: 'in-fish-curry',
    name: 'Fish Curry',
    description: 'Light and tangy fish curry in a coconut-tomato base.',
    cuisine: 'Indian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 320,
    macros: { protein: 30, carbs: 10, fats: 16 },
    servings: 3,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Fish', quantity: '450g, cut into pieces', ingredientId: 'fish' },
      { name: 'Coconut', quantity: '1/2 cup, grated', ingredientId: 'coconut' },
      { name: 'Tomato', quantity: '2, chopped', ingredientId: 'tomato' },
      { name: 'Turmeric', quantity: '1/2 tsp', ingredientId: 'turmeric' },
      { name: 'Tamarind', quantity: 'small ball', ingredientId: 'tamarind' },
    ],
    steps: [
      { text: 'Marinate fish with turmeric and salt.', minutes: 10 },
      { text: 'Grind coconut and tomato into a smooth paste.', minutes: 5 },
      { text: 'Simmer paste with tamarind water until fragrant.', minutes: 8 },
      { text: 'Gently slide in fish, simmer 8-10 minutes without stirring hard.', minutes: 10 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'in-butter-chicken',
    name: 'Butter Chicken',
    description: 'Creamy tomato-cashew gravy with tandoor-charred chicken.',
    cuisine: 'Indian',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 440,
    macros: { protein: 30, carbs: 16, fats: 28 },
    servings: 3,
    totalTimeMinutes: 45,
    ingredients: [
      { name: 'Chicken', quantity: '500g, boneless', ingredientId: 'chicken' },
      { name: 'Tomato', quantity: '4, pureed', ingredientId: 'tomato' },
      { name: 'Curd', quantity: '1/2 cup', ingredientId: 'curd' },
      { name: 'Ginger', quantity: '1 inch', ingredientId: 'ginger' },
      { name: 'Garlic', quantity: '5 cloves', ingredientId: 'garlic' },
    ],
    steps: [
      { text: 'Marinate chicken in curd, ginger-garlic and spices for 30 minutes.', minutes: 30 },
      { text: 'Grill or pan-sear chicken until charred at edges.', minutes: 10 },
      { text: 'Simmer tomato puree with butter until thick and glossy.', minutes: 12 },
      { text: 'Add chicken and a swirl of cream, simmer 5 minutes.', minutes: 5 },
    ],
    tags: ['Protein-Rich'],
  },

  // ---------------- Western · Vegetarian ----------------
  {
    id: 'ws-oats-porridge',
    name: 'Berry Oats Porridge',
    description: 'Creamy oats simmered in milk, topped with fruit.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast'],
    baseCalories: 260,
    macros: { protein: 10, carbs: 42, fats: 6 },
    servings: 1,
    totalTimeMinutes: 12,
    ingredients: [
      { name: 'Oats', quantity: '1/2 cup', ingredientId: 'oats' },
      { name: 'Milk', quantity: '1 cup', ingredientId: 'milk' },
      { name: 'Banana', quantity: '1, sliced', ingredientId: 'banana' },
      { name: 'Flax Seeds', quantity: '1 tsp', ingredientId: 'flax-seeds' },
    ],
    steps: [
      { text: 'Simmer oats in milk on low heat, stirring occasionally.', minutes: 7 },
      { text: 'Cook until creamy and thickened to taste.', minutes: 3 },
      { text: 'Top with banana slices and flax seeds before serving.', minutes: 2 },
    ],
    tags: ['High Fiber', 'Low Sugar'],
  },
  {
    id: 'ws-veg-sandwich',
    name: 'Grilled Veg Sandwich',
    description: 'Whole-grain sandwich loaded with fresh vegetables.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Breakfast', 'Evening Snack', 'Lunch'],
    baseCalories: 300,
    macros: { protein: 10, carbs: 40, fats: 11 },
    servings: 1,
    totalTimeMinutes: 15,
    ingredients: [
      { name: 'Whole-grain Bread', quantity: '2 slices' },
      { name: 'Cucumber', quantity: '1/2, sliced' },
      { name: 'Tomato', quantity: '1, sliced', ingredientId: 'tomato' },
      { name: 'Capsicum', quantity: '1/2, sliced', ingredientId: 'capsicum' },
      { name: 'Cheese', quantity: '1 slice (optional)' },
    ],
    steps: [
      { text: 'Layer vegetables and cheese between bread slices.', minutes: 5 },
      { text: 'Butter the outer sides lightly.', minutes: 2 },
      { text: 'Grill on a pan or sandwich press until golden and crisp.', minutes: 6 },
      { text: 'Slice diagonally and serve warm.', minutes: 2 },
    ],
    tags: ['Balanced'],
  },
  {
    id: 'ws-greek-salad',
    name: 'Greek Salad',
    description: 'Crisp cucumber, tomato and feta tossed in olive oil.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner', 'Evening Snack'],
    baseCalories: 240,
    macros: { protein: 8, carbs: 14, fats: 18 },
    servings: 2,
    totalTimeMinutes: 15,
    ingredients: [
      { name: 'Cucumber', quantity: '1, diced' },
      { name: 'Tomato', quantity: '2, diced', ingredientId: 'tomato' },
      { name: 'Capsicum', quantity: '1, diced', ingredientId: 'capsicum' },
      { name: 'Feta / Paneer', quantity: '100g, cubed', ingredientId: 'paneer' },
      { name: 'Olive Oil', quantity: '2 tbsp', ingredientId: 'olive-oil' },
    ],
    steps: [
      { text: 'Chop all vegetables into bite-sized pieces.', minutes: 8 },
      { text: 'Toss together with cubed cheese.', minutes: 2 },
      { text: 'Dress with olive oil, lemon, oregano, salt and pepper.', minutes: 3 },
      { text: 'Chill 5 minutes before serving for best flavour.', minutes: 5 },
    ],
    tags: ['Low Carbs', 'Low Sugar'],
  },
  {
    id: 'ws-veg-stirfry',
    name: 'Vegetable Stir Fry',
    description: 'Crunchy vegetables tossed quickly in a light garlic sauce.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 220,
    macros: { protein: 7, carbs: 24, fats: 11 },
    servings: 2,
    totalTimeMinutes: 18,
    ingredients: [
      { name: 'Broccoli', quantity: '1 cup, florets', ingredientId: 'broccoli' },
      { name: 'Capsicum', quantity: '1, sliced', ingredientId: 'capsicum' },
      { name: 'Carrot', quantity: '1, julienned' },
      { name: 'Garlic', quantity: '3 cloves', ingredientId: 'garlic' },
      { name: 'Olive Oil', quantity: '1 tbsp', ingredientId: 'olive-oil' },
    ],
    steps: [
      { text: 'Heat oil in a wok, sauté garlic until fragrant.', minutes: 2 },
      { text: 'Add harder vegetables first, stir-fry on high heat.', minutes: 5 },
      { text: 'Add remaining vegetables, toss continuously to keep crunch.', minutes: 5 },
      { text: 'Season with soy sauce and pepper, serve immediately.', minutes: 2 },
    ],
    tags: ['Low Carbs', 'High Fiber'],
  },
  {
    id: 'ws-quinoa-salad',
    name: 'Quinoa Salad Bowl',
    description: 'Protein-rich quinoa tossed with fresh vegetables and lemon.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 320,
    macros: { protein: 12, carbs: 46, fats: 9 },
    servings: 2,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Quinoa', quantity: '1 cup', ingredientId: 'quinoa' },
      { name: 'Cucumber', quantity: '1, diced' },
      { name: 'Tomato', quantity: '1, diced', ingredientId: 'tomato' },
      { name: 'Almonds', quantity: '2 tbsp, sliced', ingredientId: 'almonds' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
    ],
    steps: [
      { text: 'Rinse and cook quinoa until fluffy; cool slightly.', minutes: 15 },
      { text: 'Toss with diced vegetables and almonds.', minutes: 5 },
      { text: 'Dress with lemon juice, olive oil, salt and pepper.', minutes: 3 },
      { text: 'Chill 5 minutes for flavours to combine.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'High Fiber'],
  },
  {
    id: 'ws-avocado-toast',
    name: 'Avocado Toast',
    description: 'Toasted bread topped with mashed avocado and chilli flakes.',
    cuisine: 'Western',
    dietType: 'vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast', 'Evening Snack'],
    baseCalories: 260,
    macros: { protein: 6, carbs: 28, fats: 15 },
    servings: 1,
    totalTimeMinutes: 10,
    ingredients: [
      { name: 'Whole-grain Bread', quantity: '2 slices' },
      { name: 'Avocado', quantity: '1, ripe' },
      { name: 'Lemon', quantity: '1/2', ingredientId: 'lemon' },
      { name: 'Chilli Flakes', quantity: 'a pinch' },
    ],
    steps: [
      { text: 'Toast bread slices until golden and crisp.', minutes: 4 },
      { text: 'Mash avocado with lemon juice, salt and pepper.', minutes: 3 },
      { text: 'Spread generously over toast.', minutes: 1 },
      { text: 'Finish with chilli flakes and a drizzle of olive oil.', minutes: 2 },
    ],
    tags: ['Low Sugar', 'High Fiber'],
  },

  // ---------------- Western · Non-Vegetarian ----------------
  {
    id: 'ws-grilled-chicken-salad',
    name: 'Grilled Chicken Salad',
    description: 'Lean grilled chicken over crisp greens with a light dressing.',
    cuisine: 'Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 360,
    macros: { protein: 36, carbs: 12, fats: 18 },
    servings: 2,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Chicken Breast', quantity: '300g', ingredientId: 'chicken' },
      { name: 'Lettuce / Spinach', quantity: '2 cups', ingredientId: 'spinach' },
      { name: 'Tomato', quantity: '1, diced', ingredientId: 'tomato' },
      { name: 'Cucumber', quantity: '1, diced' },
      { name: 'Olive Oil', quantity: '1 tbsp', ingredientId: 'olive-oil' },
    ],
    steps: [
      { text: 'Season chicken breast and grill or pan-sear until cooked through.', minutes: 14 },
      { text: 'Rest chicken 5 minutes, then slice.', minutes: 5 },
      { text: 'Toss greens, tomato and cucumber together.', minutes: 4 },
      { text: 'Top with sliced chicken and drizzle with olive oil and lemon.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'ws-scrambled-eggs',
    name: 'Scrambled Eggs & Veggies',
    description: 'Fluffy scrambled eggs with sautéed peppers and onion.',
    cuisine: 'Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast'],
    baseCalories: 280,
    macros: { protein: 18, carbs: 8, fats: 20 },
    servings: 1,
    totalTimeMinutes: 12,
    ingredients: [
      { name: 'Egg', quantity: '3', ingredientId: 'egg' },
      { name: 'Capsicum', quantity: '1/2, diced', ingredientId: 'capsicum' },
      { name: 'Onion', quantity: '1/4, diced', ingredientId: 'onion' },
      { name: 'Milk', quantity: '2 tbsp', ingredientId: 'milk' },
    ],
    steps: [
      { text: 'Sauté onion and capsicum until soft.', minutes: 4 },
      { text: 'Whisk eggs with milk, salt and pepper.', minutes: 2 },
      { text: 'Pour into pan, stir gently over low heat until just set.', minutes: 5 },
      { text: 'Serve immediately while soft and creamy.', minutes: 1 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'ws-baked-fish',
    name: 'Baked Lemon Fish',
    description: 'Oven-baked fish fillet with lemon, herbs and olive oil.',
    cuisine: 'Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 320,
    macros: { protein: 34, carbs: 4, fats: 18 },
    servings: 2,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Fish Fillet', quantity: '400g', ingredientId: 'fish' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
      { name: 'Garlic', quantity: '3 cloves', ingredientId: 'garlic' },
      { name: 'Olive Oil', quantity: '2 tbsp', ingredientId: 'olive-oil' },
    ],
    steps: [
      { text: 'Preheat oven to 200°C; pat fish dry and place on a tray.', minutes: 5 },
      { text: 'Rub with garlic, olive oil, lemon zest and herbs.', minutes: 5 },
      { text: 'Bake 15-18 minutes until fish flakes easily.', minutes: 18 },
      { text: 'Finish with a squeeze of fresh lemon juice.', minutes: 2 },
    ],
    tags: ['Protein-Rich', 'Low Carbs'],
  },
  {
    id: 'ws-chicken-sandwich',
    name: 'Chicken Sandwich',
    description: 'Shredded spiced chicken layered in toasted bread.',
    cuisine: 'Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Breakfast', 'Lunch', 'Evening Snack'],
    baseCalories: 380,
    macros: { protein: 28, carbs: 36, fats: 14 },
    servings: 1,
    totalTimeMinutes: 20,
    ingredients: [
      { name: 'Chicken', quantity: '150g, cooked and shredded', ingredientId: 'chicken' },
      { name: 'Whole-grain Bread', quantity: '2 slices' },
      { name: 'Lettuce', quantity: '2 leaves' },
      { name: 'Tomato', quantity: '1, sliced', ingredientId: 'tomato' },
    ],
    steps: [
      { text: 'Season and cook chicken until done; shred into pieces.', minutes: 12 },
      { text: 'Toast bread slices lightly.', minutes: 3 },
      { text: 'Layer lettuce, tomato and chicken between slices.', minutes: 3 },
      { text: 'Press together and slice diagonally.', minutes: 2 },
    ],
    tags: ['Protein-Rich'],
  },

  // ---------------- Indo-Western · Vegetarian ----------------
  {
    id: 'iw-paneer-wrap',
    name: 'Paneer Tikka Wrap',
    description: 'Spiced grilled paneer rolled in a soft tortilla with slaw.',
    cuisine: 'Indo-Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Evening Snack', 'Dinner'],
    baseCalories: 360,
    macros: { protein: 18, carbs: 38, fats: 15 },
    servings: 1,
    totalTimeMinutes: 25,
    ingredients: [
      { name: 'Paneer', quantity: '150g, cubed', ingredientId: 'paneer' },
      { name: 'Curd', quantity: '2 tbsp', ingredientId: 'curd' },
      { name: 'Capsicum', quantity: '1/2, sliced', ingredientId: 'capsicum' },
      { name: 'Tortilla / Roti', quantity: '1 large' },
      { name: 'Onion', quantity: '1/4, sliced', ingredientId: 'onion' },
    ],
    steps: [
      { text: 'Marinate paneer and capsicum in curd and tikka spices.', minutes: 10 },
      { text: 'Pan-sear or grill until lightly charred.', minutes: 8 },
      { text: 'Warm the tortilla on a dry pan.', minutes: 3 },
      { text: 'Fill with grilled paneer, onion and mint chutney; roll tightly.', minutes: 4 },
    ],
    tags: ['Protein-Rich', 'Balanced'],
  },
  {
    id: 'iw-masala-pasta',
    name: 'Masala Pasta',
    description: 'Pasta tossed in an Indian-spiced tomato sauce.',
    cuisine: 'Indo-Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 400,
    macros: { protein: 12, carbs: 62, fats: 12 },
    servings: 2,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Pasta', quantity: '200g' },
      { name: 'Tomato', quantity: '2, pureed', ingredientId: 'tomato' },
      { name: 'Capsicum', quantity: '1, diced', ingredientId: 'capsicum' },
      { name: 'Onion', quantity: '1, chopped', ingredientId: 'onion' },
      { name: 'Garlic', quantity: '4 cloves', ingredientId: 'garlic' },
    ],
    steps: [
      { text: 'Boil pasta until al dente; reserve some starchy water.', minutes: 12 },
      { text: 'Sauté onion, garlic and capsicum until fragrant.', minutes: 6 },
      { text: 'Add tomato puree and Indian spice blend, simmer.', minutes: 8 },
      { text: 'Toss in pasta with reserved water to loosen sauce.', minutes: 4 },
    ],
    tags: ['Balanced'],
  },
  {
    id: 'iw-burrito-bowl',
    name: 'Veggie Burrito Bowl',
    description: 'Rice bowl with beans, grilled vegetables and salsa.',
    cuisine: 'Indo-Western',
    dietType: 'vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 380,
    macros: { protein: 14, carbs: 56, fats: 11 },
    servings: 2,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Rice', quantity: '1 cup', ingredientId: 'rice' },
      { name: 'Chickpeas', quantity: '1 cup, boiled', ingredientId: 'chickpeas' },
      { name: 'Capsicum', quantity: '1, sliced', ingredientId: 'capsicum' },
      { name: 'Tomato', quantity: '1, diced', ingredientId: 'tomato' },
      { name: 'Onion', quantity: '1/2, sliced', ingredientId: 'onion' },
    ],
    steps: [
      { text: 'Cook rice until fluffy.', minutes: 15 },
      { text: 'Sauté capsicum and onion with cumin until charred at edges.', minutes: 8 },
      { text: 'Warm chickpeas with a pinch of chilli powder.', minutes: 5 },
      { text: 'Assemble bowl with rice, chickpeas, vegetables and fresh salsa.', minutes: 3 },
    ],
    tags: ['High Fiber', 'Balanced'],
  },
  {
    id: 'iw-sprouts-salad',
    name: 'Sprouts & Sweet Corn Salad',
    description: 'Crunchy sprouted moong tossed with corn, lemon and chaat masala.',
    cuisine: 'Indo-Western',
    dietType: 'vegetarian',
    suitableSlots: ['Pre-breakfast', 'Evening Snack'],
    baseCalories: 200,
    macros: { protein: 11, carbs: 30, fats: 4 },
    servings: 2,
    totalTimeMinutes: 15,
    ingredients: [
      { name: 'Mixed Sprouts', quantity: '1.5 cups', ingredientId: 'sprouts' },
      { name: 'Sweet Corn', quantity: '1/2 cup' },
      { name: 'Tomato', quantity: '1, diced', ingredientId: 'tomato' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
    ],
    steps: [
      { text: 'Steam sprouts lightly for 4-5 minutes; cool.', minutes: 5 },
      { text: 'Toss with corn, tomato and onion.', minutes: 4 },
      { text: 'Dress with lemon juice, chaat masala and coriander.', minutes: 3 },
      { text: 'Chill briefly before serving.', minutes: 3 },
    ],
    tags: ['Protein-Rich', 'High Fiber', 'Low Sugar'],
  },

  // ---------------- Indo-Western · Non-Vegetarian ----------------
  {
    id: 'iw-chicken-wrap',
    name: 'Chicken Tikka Wrap',
    description: 'Char-grilled chicken tikka rolled with slaw and mint chutney.',
    cuisine: 'Indo-Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Evening Snack', 'Dinner'],
    baseCalories: 400,
    macros: { protein: 30, carbs: 36, fats: 15 },
    servings: 1,
    totalTimeMinutes: 30,
    ingredients: [
      { name: 'Chicken', quantity: '200g, cubed', ingredientId: 'chicken' },
      { name: 'Curd', quantity: '3 tbsp', ingredientId: 'curd' },
      { name: 'Tortilla / Roti', quantity: '1 large' },
      { name: 'Onion', quantity: '1/4, sliced', ingredientId: 'onion' },
      { name: 'Capsicum', quantity: '1/2, sliced', ingredientId: 'capsicum' },
    ],
    steps: [
      { text: 'Marinate chicken in curd and tikka spices for 20 minutes.', minutes: 20 },
      { text: 'Grill or pan-sear until charred and cooked through.', minutes: 10 },
      { text: 'Warm the tortilla and layer with onion, capsicum and chutney.', minutes: 3 },
      { text: 'Add grilled chicken and roll tightly.', minutes: 3 },
    ],
    tags: ['Protein-Rich'],
  },
  {
    id: 'iw-egg-bhurji-toast',
    name: 'Egg Bhurji Toast',
    description: 'Spiced Indian scrambled eggs piled onto buttered toast.',
    cuisine: 'Indo-Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Pre-breakfast', 'Breakfast'],
    baseCalories: 300,
    macros: { protein: 18, carbs: 24, fats: 16 },
    servings: 1,
    totalTimeMinutes: 15,
    ingredients: [
      { name: 'Egg', quantity: '3', ingredientId: 'egg' },
      { name: 'Onion', quantity: '1/2, chopped', ingredientId: 'onion' },
      { name: 'Tomato', quantity: '1/2, chopped', ingredientId: 'tomato' },
      { name: 'Whole-grain Bread', quantity: '2 slices' },
    ],
    steps: [
      { text: 'Sauté onion and tomato with turmeric and chilli.', minutes: 5 },
      { text: 'Add whisked eggs, scramble on medium heat until cooked.', minutes: 5 },
      { text: 'Toast bread slices until golden.', minutes: 3 },
      { text: 'Pile bhurji onto toast and serve hot.', minutes: 2 },
    ],
    tags: ['Protein-Rich'],
  },
  {
    id: 'iw-tandoori-bowl',
    name: 'Tandoori Chicken Bowl',
    description: 'Smoky tandoori chicken over herbed rice with a yogurt drizzle.',
    cuisine: 'Indo-Western',
    dietType: 'non-vegetarian',
    suitableSlots: ['Lunch', 'Dinner'],
    baseCalories: 420,
    macros: { protein: 34, carbs: 44, fats: 14 },
    servings: 2,
    totalTimeMinutes: 40,
    ingredients: [
      { name: 'Chicken', quantity: '350g', ingredientId: 'chicken' },
      { name: 'Curd', quantity: '3 tbsp', ingredientId: 'curd' },
      { name: 'Rice', quantity: '1 cup', ingredientId: 'rice' },
      { name: 'Lemon', quantity: '1', ingredientId: 'lemon' },
      { name: 'Coriander Leaves', quantity: '2 tbsp', ingredientId: 'coriander-leaves' },
    ],
    steps: [
      { text: 'Marinate chicken in curd, lemon and tandoori spices for 20 minutes.', minutes: 20 },
      { text: 'Grill or bake until charred and cooked through.', minutes: 18 },
      { text: 'Cook rice with a bay leaf until fluffy.', minutes: 15 },
      { text: 'Assemble bowl with rice, sliced chicken, herbs and a yogurt drizzle.', minutes: 4 },
    ],
    tags: ['Protein-Rich', 'Balanced'],
  },
]
